language: node_js
node_js:
  - "12"
env:
  - NODE_ENV=test
install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codecov
script:
  - istanbul cover /home/travis/.nvm/versions/node/v12.4.0/lib/node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov