language: node_js
node_js:
  - "12"
env:
  - NODE_ENV=test
install:
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g codecov
  - mkdir .nyc_output
script:
  - npm run test
  - npm run report-coverage
